RestAssured is ready
AleksandrDark/AleksandrShilovAPI pull request #3
Opened 2021-10-22 14:00 UTC by AleksandrDark

Please, take a look at my work

2021-10-25 08:25 UTC, GrebNat requested changes

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/dto/CardTrelloDTO.java
> +
empty line

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/dto/ListTrelloDTO.java
> +
empty line

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/BoardTrelloService.java
> +
empty line

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/BoardTrelloService.java
> +    private BoardTrelloDTO parseBoardTrello(Response response) {
move private to the bottom

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/BoardTrelloService.java
> +
empty line

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/CardTrelloService.java
> +    private CardTrelloDTO parseCardTrello(Response response) {
there is same method for board. could be moved to CommonService

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/CommonService.java
> +            .addQueryParam("key", PropertyReader.getProperties().get("trelloKey").toString())
update to 
PropertyReader.getTrelloKey()

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/CommonService.java
> +
empty line

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/CommonService.java
> +    }
code duplication for in 2 methods above. call one method from other with empty params.

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/util/URI.java
> +    public static final String BASE_URL = "https://api.trello.com/";
move to tests.properties

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/ListTrelloService.java
> +}
same comments like for Card... class

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/service/CommonService.java
> +    }
code duplication for in 2 methods above. call one method from other with empty params.

2021-10-25 08:25 UTC, GrebNat commented on src/main/java/util/URI.java
> +    public static String ENDPOINT_BOARD = "1/boards/";
separate board/card/list endpoint for  CREATE and GET 
 "1/boards/"
  "1/boards/{0}"

2021-10-25 08:25 UTC, GrebNat commented on src/test/java/assertions/AssertionsTrello.java
> +
add error messages for all assetiongs

2021-10-25 08:25 UTC, GrebNat commented on src/test/java/assertions/AssertionsTrello.java
> +
move assertion class into the main

2021-10-25 08:25 UTC, GrebNat commented on src/test/java/functionalteststrello/TrelloTest.java
> +        String idBoard = boardTrelloDTO.getId();
test naming and test steps are inconsistent

2021-10-25 08:25 UTC, GrebNat commented on src/test/java/functionalteststrello/TrelloTest.java
> +        String idBoard = boardTrelloDTO.getId();
board should be created into the test. There should not be any hidden steps

2021-10-26 06:36 UTC, GrebNat requested changes

2021-10-26 06:36 UTC, GrebNat commented on src/main/java/util/PropertyReader.java
> +        return PropertyReader.getProperties("properties/conf.properties").get("trelloKey").toString();
pls, do not read file with properties every time. Read it once, at the first request

2021-10-26 06:36 UTC, GrebNat commented on src/test/resources/properties/test.properties
> +BASE_URL=https://api.trello.com/
it is ok to combine conf.properties and test.properties files

2021-10-26 06:36 UTC, GrebNat commented on src/test/java/functionalteststrello/TrelloTest.java
> +        System.out.println(boardTrelloService);
why ??

2021-10-26 12:52 UTC, AleksandrDark commented on src/test/java/functionalteststrello/TrelloTest.java
> +        System.out.println(boardTrelloService);
it is my mistake. I forgot to delete the unnecessary lines

2021-10-26 13:39 UTC, GrebNat approved these changes

2021-10-26 17:09 UTC, merged